version: '3.8'

services:
  php-container:
    image: alexandershuld/php-server
    ports:
      - "8081:80"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role==worker

  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/correct
      MYSQL_DATABASE: flowers
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-data-for-php-entry:/docker-entrypoint-initdb.d
    secrets:
      - correct
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager

secrets:
  correct:
    external: true

volumes:
  db_data:
